coverage.info=coverage.json
base.dir=/home/mario/Desktop/LogicFL/defects4j/Mockito-18
source.path=buggy/src:fixed/test
class.path=../../lib/*:../../d4j-lib/lib/junit-4.11.jar:lib/Mockito-18_buggy_src.jar:lib/Mockito-18_fixed_test.jar:../../d4j-lib/Mockito/lib/asm-all-5.0.4.jar:../../d4j-lib/Mockito/lib/assertj-core-2.1.0.jar:../../d4j-lib/Mockito/lib/cglib-and-asm-1.0.jar:../../d4j-lib/Mockito/lib/cobertura-2.0.3.jar:../../d4j-lib/Mockito/lib/fest-assert-1.3.jar:../../d4j-lib/Mockito/lib/fest-util-1.1.4.jar:../../d4j-lib/Mockito/lib/hamcrest-all-1.3.jar:../../d4j-lib/Mockito/lib/hamcrest-core-1.1.jar:../../d4j-lib/Mockito/lib/objenesis-2.1.jar:../../d4j-lib/Mockito/lib/objenesis-2.2.jar:../../d4j-lib/Mockito/lib/powermock-reflect-1.2.5.jar:/data/defects4j/subjects/Mockito/Mockito-18/compileLib/byte-buddy-0.6.8.jar
tests.info=tests.json
output.dir=result
jvm=/usr/bin/java
junit.version=junit4
jacoco.path=../../lib/jacocoagent.jar
jacoco.exec=jacoco.exec
target.prefix=org.mockito
npe.info.path=npe.traces.json
facts.pl=logic-fl.pl
rules.pl=../../lib/npe-rules.pl
print.debug.info=false
monitor.target=trace
covered.only=true
