coverage.info=coverage.json
base.dir=/home/mario/Desktop/LogicFL/defects4j/Gson-6
source.path=buggy/gson/src/main/java:fixed/gson/src/test/java
class.path=../../lib/*:lib/Gson-6_buggy_src.jar:lib/Gson-6_fixed_test.jar
tests.info=tests.json
output.dir=result
jvm=/usr/bin/java
junit.version=junit4
jacoco.path=../../lib/jacocoagent.jar
jacoco.exec=jacoco.exec
target.prefix=com.google.gson
npe.info.path=npe.traces.json
facts.pl=logic-fl.pl
rules.pl=../../lib/npe-rules.pl
print.debug.info=false
covered.only=true
monitor.target=trace
