coverage.info=coverage.json
base.dir=/home/mario/Desktop/LogicFL/defects4j/Closure-171
source.path=buggy/src:fixed/test
class.path=../../lib/*:lib/Closure-171_buggy_src.jar:lib/args4j.jar:lib/guava.jar:lib/json.jar:lib/jsr305.jar:lib/protobuf-java.jar:lib/rhino.jar:lib/ant.jar:lib/ant-launcher.jar:lib/caja-r4314.jar:lib/jarjar.jar:lib/junit.jar:lib/Closure-171_fixed_test.jar
tests.info=tests.json
output.dir=result
jvm=/usr/bin/java
junit.version=junit4
jacoco.path=../../lib/jacocoagent.jar
jacoco.exec=jacoco.exec
target.prefix=com.google.javascript
npe.info.path=npe.traces.json
facts.pl=logic-fl.pl
rules.pl=../../lib/npe-rules.pl
print.debug.info=false
covered.only=true
monitor.target=trace
