coverage.info=coverage.json
base.dir=/home/mario/Desktop/LogicFL/defects4j/Lang-47
source.path=buggy/src/java:fixed/src/test
class.path=../../lib/*:lib/Lang-47_buggy_src.jar:lib/Lang-47_fixed_test.jar
tests.info=tests.json
output.dir=result
jvm=/usr/bin/java
junit.version=junit4
jacoco.path=../../lib/jacocoagent.jar
jacoco.exec=jacoco.exec
target.prefix=org.apache.commons.lang
npe.info.path=npe.traces.json
facts.pl=logic-fl.pl
rules.pl=../../lib/npe-rules.pl
print.debug.info=false
covered.only=true
monitor.target=trace
