"""Semantic Validation Layer — Intervento 5 (LLM-as-Judge).

After a patch passes the test suite, this module performs a second LLM call
that acts as an independent judge: it checks whether the patch preserves the
method's documented contract (Javadoc) and is semantically correct.

This catches "test-suite blindness" failures, i.e., patches that pass the
test suite but violate the API contract:
  - Csv-4:        return this.headerMap  →  violates @return a copy
  - Jsoup-8:      throw IllegalStateException in ownerDocument()
                  →  violates @return "or null if there is no such Document"
  - Csv-11:       throws IllegalArgumentException  →  not in original contract

The validator inspects EVERY method modified by the patch (not just the
primary fault location): the contract violation often lives in a collateral
edit, as in Jsoup-8. Methods without a Javadoc are skipped — without a
documented contract the judge cannot make a meaningful judgement, and
silence is safer than a spurious rejection.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from fault_oracle.ast_extractor import (
    _parse_java,
    extract_javadoc_from_lines,
)
from services.sandbox_evaluator import read_source_roots


# ── Prompt templates ──────────────────────────────────────────────────────────

JUDGE_SYSTEM_PROMPT = """\
You are a senior Java code reviewer specialising in API contracts and semantic correctness.

A patch has been generated by an automated repair tool and has PASSED the test suite.
Your job is to determine whether the patch is *semantically valid*:
it does NOT violate the method's Javadoc contract even if tests pass.

Common violations to detect:
1. @return contract:   the patched method returns something different from what the Javadoc specifies
   (e.g., returns an internal reference when @return says "a copy"; returns a non-null dummy
   object when @return says "null if not present").
2. Encapsulation:      exposes a mutable internal field that should be defensively copied.
3. @throws contract:   introduces or suppresses exceptions not documented in the Javadoc.
4. Semantic shortcut:  uses a workaround (e.g., new EmptyObject()) that passes tests but is
   architecturally wrong according to the class contract.

Be STRICT on contract violations. Be FAIR on minimal, correct fixes.
If Javadoc is absent or ambiguous, lean toward VALID.

IMPORTANT — what is NOT a violation:
- A null-guard that returns null (or skips work) when internal state is
  absent is VALID even if @return does not explicitly mention null: judge
  the @return clause against the NORMAL (non-null) path. Human fixes for
  NullPointerExceptions routinely add exactly this guard.
- Judge only what the patch CHANGED. Pre-existing behaviour kept intact is
  never a violation, even if questionable.

Respond ONLY with valid JSON (no markdown, no prose):
{"valid": true, "reason": "one-sentence explanation"}
or
{"valid": false, "reason": "specific contract violation"}
"""

JUDGE_USER_TEMPLATE = """\
## Method under review: `{method_name}` in `{class_name}`

### Javadoc Contract (the law — fix MUST comply)
```java
{javadoc}
```

### Original (buggy) method
```java
{original_method}
```

### Patched method (passed tests — is it semantically valid?)
```java
{patched_method}
```

### Repair context
- **Bug description:** {flawed_behavior}
- **Intended fix:** {minimal_fix}
{static_warnings}
### Your task
Check the patched method against the Javadoc contract.
Focus especially on the @return clause, any new `throw` statements, and
encapsulation concerns. Respond with JSON only.
"""


# ── Result dataclass ──────────────────────────────────────────────────────────

@dataclass
class ValidationResult:
    """Outcome of the semantic validation step."""

    valid: bool
    """True if the patch is semantically valid (passes contract check)."""

    reason: str
    """One-sentence explanation from the judge."""

    skipped: bool = False
    """True if validation was skipped (e.g., no Javadoc available)."""

    checked_methods: List[str] = field(default_factory=list)
    """Names of the modified methods that were actually judged."""


@dataclass
class ModifiedMethod:
    """A method whose source changed between the original and patched tree."""

    class_name: str
    method_name: str
    original_source: str
    patched_source: str
    javadoc: str
    file_rel: str = ""
    static_warnings: List[str] = field(default_factory=list)
    """Soft signals from static heuristics, surfaced to the judge."""


# ── Diff collection ───────────────────────────────────────────────────────────

def _method_nodes_by_signature(source: str) -> Dict[Tuple[str, int], object]:
    """Map (method_name, param_count) → tree-sitter node for a Java source."""
    tree = _parse_java(source)
    if tree is None:
        return {}

    nodes: Dict[Tuple[str, int], object] = {}
    stack = [tree.root_node]
    while stack:
        node = stack.pop()
        if node.type in ("method_declaration", "constructor_declaration"):
            name_node = node.child_by_field_name("name")
            params = node.child_by_field_name("parameters")
            count = -1
            if params is not None:
                count = sum(
                    1 for c in params.named_children
                    if c.type in ("formal_parameter", "spread_parameter")
                )
            if name_node:
                key = (name_node.text.decode("utf-8"), count)
                # In case of nested classes with same signature, keep the first
                nodes.setdefault(key, node)
        for child in node.children:
            stack.append(child)
    return nodes


def _normalised(code: str) -> str:
    """Whitespace-insensitive representation of a code block."""
    return "\n".join(line.strip() for line in code.splitlines() if line.strip())


def collect_modified_methods(
    original_root: Path,
    patched_dir: Path,
) -> List[ModifiedMethod]:
    """Find every method whose body changed between original_root and patched_dir.

    patched_dir is a full copy of original_root (see PatchAgent._create_patched_copy),
    so files correspond 1:1 by relative path.
    """
    modified: List[ModifiedMethod] = []

    for patched_file in patched_dir.rglob("*.java"):
        rel = patched_file.relative_to(patched_dir)
        original_file = original_root / rel
        if not original_file.exists():
            continue  # file added from scratch — out of scope for method diffing

        patched_src = patched_file.read_text(encoding="utf-8", errors="replace")
        original_src = original_file.read_text(encoding="utf-8", errors="replace")
        if patched_src == original_src:
            continue

        original_lines = original_src.splitlines()
        before = _method_nodes_by_signature(original_src)
        after = _method_nodes_by_signature(patched_src)

        class_name = rel.stem

        for key, after_node in after.items():
            before_node = before.get(key)
            patched_method = patched_src[after_node.start_byte:after_node.end_byte]
            if before_node is not None:
                original_method = original_src[before_node.start_byte:before_node.end_byte]
                if _normalised(original_method) == _normalised(patched_method):
                    continue
                javadoc = extract_javadoc_from_lines(
                    original_lines, before_node.start_point[0] + 1
                )
            else:
                original_method = "(method added by the patch)"
                javadoc = ""

            modified.append(ModifiedMethod(
                class_name=class_name,
                method_name=key[0],
                original_source=original_method,
                patched_source=patched_method,
                javadoc=javadoc,
                file_rel=str(rel),
            ))

    return modified


# ── Validator ─────────────────────────────────────────────────────────────────

class SemanticValidator:
    """LLM-as-Judge for post-patch contract validation.

    Usage:
        validator = SemanticValidator(client)
        result = validator.validate(patched_dir, repair_spec, bug_dir)
        if not result.valid:
            # reject the patch — treat as SEMANTIC_FAIL for retry purposes
            ...
    """

    MAX_JUDGED_METHODS = 3
    """Cost cap: judge at most this many modified methods per patch."""

    def __init__(self, client=None):
        from services.azure_client import AzureClient
        self.client = client or AzureClient()

    def validate(
        self,
        patched_dir: Path,
        repair_spec,        # RepairSpec
        bug_dir: Path,
        static_warnings: Optional[Dict[str, List[str]]] = None,
    ) -> ValidationResult:
        """Run the judge LLM on a patch that has already passed the test suite.

        Inspects every modified method that has a Javadoc contract. Returns a
        ValidationResult; if validation cannot be performed (no modified
        methods with Javadoc, LLM error), returns valid=True with skipped=True
        so that the patch is not falsely rejected.

        Args:
            patched_dir: The patched source copy for this attempt.
            repair_spec: RepairSpec from Phase 2 (context for the judge).
            bug_dir: The bug directory (to resolve the original source root).
            static_warnings: Optional {method_name: [warning, ...]} soft signals
                from guard_rails to surface to the judge.
        """
        source_roots = read_source_roots(bug_dir)
        if not source_roots:
            return ValidationResult(
                valid=True,
                reason="No source roots found — validation skipped.",
                skipped=True,
            )

        try:
            modified = collect_modified_methods(source_roots[0], patched_dir)
        except Exception as exc:
            return ValidationResult(
                valid=True,
                reason=f"Could not diff patched source ({exc}) — validation skipped.",
                skipped=True,
            )

        if not modified:
            return ValidationResult(
                valid=True,
                reason="No modified methods detected — validation skipped.",
                skipped=True,
            )

        # Judge only methods with a documented contract; warnings can force
        # a method into the judged set even without Javadoc.
        static_warnings = static_warnings or {}
        judged = [
            m for m in modified
            if m.javadoc or static_warnings.get(m.method_name)
        ]
        if not judged:
            return ValidationResult(
                valid=True,
                reason="No modified method has a Javadoc contract — validation skipped.",
                skipped=True,
            )

        judged = judged[:self.MAX_JUDGED_METHODS]
        checked: List[str] = []

        for method in judged:
            method.static_warnings = static_warnings.get(method.method_name, [])
            result = self._judge_method(method, repair_spec)
            checked.append(f"{method.class_name}.{method.method_name}")
            if result is not None and not result.valid:
                result.checked_methods = checked
                return result

        return ValidationResult(
            valid=True,
            reason=f"All {len(checked)} modified method(s) respect their contract.",
            checked_methods=checked,
        )

    # ── Internals ─────────────────────────────────────────────────────────────

    def _judge_method(self, method: ModifiedMethod, repair_spec) -> Optional[ValidationResult]:
        """Run one judge call. Returns None when the call fails (fail-open)."""
        warnings_block = ""
        if method.static_warnings:
            bullet = "\n".join(f"- {w}" for w in method.static_warnings)
            warnings_block = (
                f"\n### ⚠ Static analysis warnings (verify them)\n{bullet}\n"
            )

        user_prompt = JUDGE_USER_TEMPLATE.format(
            class_name=method.class_name,
            method_name=method.method_name,
            javadoc=method.javadoc or "(no Javadoc — judge on the warnings above)",
            original_method=method.original_source,
            patched_method=method.patched_source,
            flawed_behavior=getattr(repair_spec, "flawed_behavior", "") or "(not available)",
            minimal_fix=getattr(repair_spec, "minimal_fix", "") or "(not available)",
            static_warnings=warnings_block,
        )

        messages = [
            {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
            {"role": "user",   "content": user_prompt},
        ]

        try:
            print(f"  [semantic_validator] Judging {method.class_name}.{method.method_name} "
                  f"against its Javadoc contract...")
            response = self.client.chat(messages, temperature=0.0)
            result = self._parse_response(response)
            verdict = "✅ VALID" if result.valid else "❌ INVALID"
            print(f"  [semantic_validator] Verdict: {verdict} — {result.reason}")
            return result
        except Exception as exc:
            print(f"  [semantic_validator] WARNING: judge call failed ({exc}) — skipping")
            return None

    @staticmethod
    def _parse_response(raw: str) -> ValidationResult:
        """Parse the judge's JSON response."""
        # Strip markdown code fences if present
        cleaned = re.sub(r"```[a-z]*\n?", "", raw).strip()
        try:
            data = json.loads(cleaned)
            return ValidationResult(
                valid=bool(data.get("valid", True)),
                reason=str(data.get("reason", "")),
            )
        except json.JSONDecodeError:
            # If JSON parsing fails, be conservative: assume valid
            return ValidationResult(
                valid=True,
                reason=f"Could not parse judge response: {raw[:100]}",
                skipped=True,
            )
