coverage.info=coverage.json
base.dir=/home/mario/Desktop/LogicFL/defects4j/Csv-11
source.path=buggy/src/main/java:fixed/src/test/java
class.path=../../lib/*:lib/*
#class.path=../../lib/*:lib/Csv-11_buggy_src.jar:lib/Csv-11_fixed_test.jar
tests.info=tests.json
output.dir=result
jvm=/usr/bin/java
junit.version=junit4
jacoco.path=../../lib/jacocoagent.jar
jacoco.exec=jacoco.exec
target.prefix=org.apache.commons.csv
npe.info.path=npe.traces.json
facts.pl=logic-fl.pl
rules.pl=../../lib/npe-rules.pl
print.debug.info=false
covered.only=true
monitor.target=trace
