coverage.info=coverage.json
base.dir=/home/mario/Desktop/LogicFL/defects4j/Chart-2
source.path=buggy/source:fixed/tests
class.path=../../lib/*:lib/Chart-2_buggy_src.jar:lib/Chart-2_fixed_test.jar
tests.info=tests.json
output.dir=result
jvm=/usr/bin/java
junit.version=junit4
jacoco.path=../../lib/jacocoagent.jar
jacoco.exec=jacoco.exec
target.prefix=org.jfree
npe.info.path=npe.traces.json
facts.pl=logic-fl.pl
rules.pl=../../lib/npe-rules.pl
print.debug.info=false
monitor.target=coverage
covered.only=true
